plugins {
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'com.intershop.gradle.javacc' version '6.1.0'
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id 'signing'
    id 'com.vanniktech.maven.publish' version '0.37.0'
}
// apply plugin: 'jacoco' (fails in JDK 11 on Travis)


repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'tools.jackson.core:jackson-databind:3.2.0'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'tools.jackson.dataformat:jackson-dataformat-yaml:3.2.0'
}

ext {
    timestamp = new Date().format('yyyyMMddHHmm')
    gitrev = "git log -1 HEAD --pretty=tformat:%h".execute().text.trim()
}

group = 'com.schibsted.spt.data'
version = "0.1.15"
project.description = "A JSON query and transformation language"

check {
    doLast {
        println 'Test report in build/reports/tests/test/index.html'
    }
}

// ===========================================================================
// javacc integration
javacc {
    javaCCVersion = '7.0.10'
    configs {
        jsltParser {
            inputFile = file('src/main/jjtree/jslt.jjt')
            packageName = 'com/schibsted/spt/data/jslt/parser'
            jdkVersion = java.targetCompatibility
            jjtree {
                staticParam = false;
                trackTokens = true;
            }
            buildParser = true;
            buildTokenManager = true;
            sanityCheck = true;
            unicodeInput = true;
        }
    }
}


// ===========================================================================
// Sonatype Maven central publishing

// declaring this separately to avoid including javacc-generated sources
// because javadoc fail on those
sourceSets {
    javadoc {
        java {
            srcDirs 'src/main/java'
        }
    }
}

// make javadoc shut up about things it doesn't like
javadoc.options.addStringOption('Xdoclint:none', '-quiet')

java {
    withJavadocJar()
    withSourcesJar()
}

mavenPublishing {
  coordinates(group, "jslt", version)

  pom {
      name = 'JSLT'
      description = project.description
      url = 'https://github.com/schibsted/jslt'
      organization {
          name = 'Schibsted ASA'
          url = 'https://github.com/schibsted/'
      }
      issueManagement {
          system = 'GitHub'
          url = 'https://github.com/schibsted/jslt/issues'
      }
      licenses {
          license {
              name = 'Apache License 2.0'
              url = 'https://github.com/schibsted/jslt/blob/master/LICENSE'
              distribution = 'repo'
          }
      }
      developers {
          developer {
              name = 'Schibsted'
          }
      }
      scm {
          url = 'https://github.com/schibsted/jslt'
          connection = 'scm:git:git://github.com/schibsted/jslt.git'
          developerConnection = 'scm:git:ssh://git@github.com:schibsted/jslt.git'
      }
  }

  publishToMavenCentral()

  signAllPublications()
}

def signingKey = findProperty("signing.secretKey")
def signingPassword = findProperty("signing.password")

signing {
    useInMemoryPgpKeys(signingKey, signingPassword)
    sign publishing.publications.withType(MavenPublication)
}

tasks.withType(GenerateModuleMetadata).configureEach {
    mustRunAfter('plainJavadocJar')
}